default_connection_name = "default"

[connections.default]
account = "XG02811-OO69432"
user = "LUIS.ACEITUNO@HELLOFRESH.COM"
authenticator = "externalbrowser"
database = "SCM_ANALYTICS"
warehouse = "scm_analytics_load_medium"
schema = "PUBLIC"
role = "SCM_ANALYTICS_SA_NONSENSITIVE"

[connections.staging]
account = "XG02811-OO69432"
user = "LUIS.ACEITUNO@HELLOFRESH.COM"
authenticator = "externalbrowser"
database = "SCM_ANALYTICS_STAGING"
warehouse = "SCM_ANALYTICS_DEV"
schema = "PUBLIC"
role = "SCM_ANALYTICS_SA_NONSENSITIVE"

[connections.dev]
account = "XG02811-OO69432"
user = "LUIS.ACEITUNO@HELLOFRESH.COM"
authenticator = "externalbrowser"
database = "SCM_ANALYTICS_DEV"
warehouse = "SCM_ANALYTICS_DEV"
schema = "PUBLIC"
role = "SCM_ANALYTICS_SA_NONSENSITIVE"
